### PR TITLE
fix #321: POSTGRES_INITDB_WALDIR handling

### LINKED ISSUE #321: Tag 13-3.1 doesn't survive container recreate because waldir is missing.
When the container is recreated, it complains that the `pg_wal` directory is missing.
It turns out that the `pg_wal` directory inside the `PGDATA` directory is only a link to whatever directory specified in `POSTGRES_INITDB_WALDIR`.
I was under the impression that this env `POSTGRES_INITDB_WALDIR` is only for initializations.
It currently failed upon recreate because `POSTGRES_INITDB_WALDIR` is outside the default persistent volume.
When the container is recreated, the `pg_wal` content is lost, which is very dangerous.

Furthermore, if I specified `POSTGRES_INITDB_WALDIR` into a directory inside the persistent volume, the container is failed to initialize, because in `setup-database.sh` after directory creation, we deleted using `rm -rf ${DATADIR}` which caused the initdb waldir to be deleted again. So the postgres init, it failed to find the initdb waldir.

@NyakudyaA do you have any suggestion to fix this?
Is it ok to just move the `rm -rf ${DATADIR}` up to delete the content before the initdb waldir creation?
From what I understand by default you want the initdb waldir to be outside the default volume. However if initdb waldir is not persisted, when containers are recreated the symlink will not find the directory.

### PR DESCRIPTION
**Pull request by lucernae**
PR for issue #321 .

For the expected behavior, refer to:

https://github.com/kartoza/docker-postgis/issues/321#issuecomment-901066342

# Proposed solution

First time initialization:
- Do not set default value for POSTGRES_INITDB_WALDIR. We use the existence of the environment variable to determine if the data directory need to be initialized with separate pg waldir or not
- Nested pg_wal location under data directory is prevented by path globbing. It should exit because else the directory will be deleted on first time setup (we don't want that).

Subsequent run/recreate:
- We can't really check if the specified POSTGRES_INITDB_WALDIR corresponds to additional volume mount. We can't check it from inside the docker container, unless you use docker API. In Kubernetes, if the volume is using CSI driver, the mount will exists if we execute `df`. Let's just let the operator handle that
- We instead only check the symlink resolution of `${DATADIR}/pg_wal` to the location specified by `POSTGRES_INITDB_WALDIR`. It has to match, if not, raise warning but not exit.
- Only exits if the resolved `pg_wal` location (from the symlink) is actually empty. It's obviously the wrong folder and we don't want postgres to use the wrong folder.
- In the case of non empty resolved `pg_wal`, let postgres decide if it's the correct directory or not.

### CODE REVIEW

**Comment by lucernae** [comment]
Also optimized some caching problem with the Github Action.

File: scenario_tests/datadir_init/test.sh [hunk 1]
```diff
@@ -28,4 +28,7 @@ for service in "${services[@]}"; do
 
 done
 
+# special meta test to check the setup
+bash ./test_custom_waldir.sh
```
Comment (lucernae) [inline scenario_tests/datadir_init/test.sh:32]: Since testing the POSTGRES_INITDB_WALDIR setup requires some meta information (wether the container produce log message or not), it is executed in a different script in the host, and not as python unittest inside the container.

File: scripts/setup-database.sh [hunk 2]
```diff
@@ -3,26 +3,76 @@
...
+Can't proceed because "${DATADIR}/pg_wal" directory is empty.
+EOF
+      exit 1
+    fi
 fi;
 
 # Set proper permissions
 # needs to be done as root:
-create_dir ${WAL_ARCHIVE}
+create_dir "${WAL_ARCHIVE}"
```
Comment (lucernae) [inline scripts/setup-database.sh:75]: Just a small quote guard here because I'm paranoid.

File: scripts/setup-database.sh [hunk 3]
```diff
@@ -3,26 +3,76 @@
...
 
 POSTGRES_PASS=$(cat /tmp/PGPASSWORD.txt)
+INITDB_WALDIR_FLAG=""
+
+# Check POSTGRES_INITDB_WALDIR value
+if [[ -n "${POSTGRES_INITDB_WALDIR}" ]]; then
+    # If POSTGRES_INITDB_WALDIR is defined, make sure that it is not inside 
+    # the ${DATADIR} directory, to avoid deletions
+    case "${POSTGRES_INITDB_WALDIR}" in
+        ${DATADIR}/*)
```
Comment (lucernae) [inline scripts/setup-database.sh:13]: We use pattern match to check if `POSTGRES_INITDB_WALDIR` is a subpath of ${DATADIR}

File: scripts/setup-database.sh [hunk 4]
```diff
@@ -3,26 +3,76 @@
...
-    command="$INITDB -U postgres --pwfile=<(echo "$POSTGRES_PASS") -E ${DEFAULT_ENCODING} --lc-collate=${DEFAULT_COLLATION} --lc-ctype=${DEFAULT_CTYPE} --wal-segsize=${WAL_SEGSIZE} --auth=${PASSWORD_AUTHENTICATION} -D ${DATADIR} --waldir=${POSTGRES_INITDB_WALDIR} ${INITDB_EXTRA_ARGS}"
+    command="$INITDB -U postgres --pwfile=<(echo "$POSTGRES_PASS") -E ${DEFAULT_ENCODING} --lc-collate=${DEFAULT_COLLATION} --lc-ctype=${DEFAULT_CTYPE} --wal-segsize=${WAL_SEGSIZE} --auth=${PASSWORD_AUTHENTICATION} -D ${DATADIR} ${INITDB_WALDIR_FLAG} ${INITDB_EXTRA_ARGS}"
+    echo "$command"
     su - postgres -c "$command"
+else
+    # If using existing datadir:
+    # Check if pg_wal symlink point to the correct directory described by POSTGRES_INITDB_WALDIR.
+    # Give warning if the value is not the same
+    if [[ -n "${POSTGRES_INITDB_WALDIR}" && \
+        "$(realpath ${POSTGRES_INITDB_WALDIR})" != "$(realpath \"$(readlink ${DATADIR}/pg_wal)\")" ]]; then
```
Comment (NyakudyaA) [inline scripts/setup-database.sh]: `$(realpath \"$(readlink ${DATADIR}/pg_wal)\")` should be changed to

`$(realpath "$(readlink ${DATADIR}/pg_wal)")`

otherwise, you get the following error
error

**Comment by NyakudyaA** [comment]
I have added a comment for the logic otherwise 
LGTM

File: scripts/setup-database.sh (hunk 4 above)
Comment (lucernae) [reply scripts/setup-database.sh]: Ah, must have still pass the tests because it's just a warning and we don't check the else part.

Comment (lucernae) [reply scripts/setup-database.sh]:
```suggestion
        "$(realpath ${POSTGRES_INITDB_WALDIR})" != "$(realpath "$(readlink ${DATADIR}/pg_wal)")" ]]; then
```
