### PR TITLE
Fix #241

### LINKED ISSUE #241: Bug when creating new datadirectory.
Scenario test passed because the `DATADIR` environment variable was overwritten, but the scenario itself fails. Pretty stupid of me...

### PR DESCRIPTION
**Pull request by lucernae**
fix `DATADIR` environment variable get overshadowed

### CODE REVIEW

File: scripts/env-data.sh [hunk 1]
```diff
@@ -67,8 +67,8 @@ if [ -z "${POSTGRES_DBNAME}" ]; then
 	POSTGRES_DBNAME=gis
 fi
 # If datadir is defined use this
```
Comment (lucernae) [inline scripts/env-data.sh]:
```suggestion
# If datadir is not defined, then use this
```

**Comment by lucernae** [comment]
Minor update.
Will just merge
